name: Build and Push Docker Image

# Когда запускать? При любом пуше в ветку main
on:
  push:
    branches: [ "main" ]
    # Можно добавить paths, чтобы запускалось только если меняем файлы во 2 дне
    paths:
      - 'day02/**'
      - '.github/workflows/ci.yml'

jobs:
  build-and-push:
    # На какой машине запускать (GitHub дает бесплатные Ubuntu сервера)
    runs-on: ubuntu-latest

    steps:
      # Шаг 1: Скачать наш код
      - name: Checkout code
        uses: actions/checkout@v4

      # Шаг 2: Логинимся в Docker Hub (используя секреты)
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Шаг 3: Настройка Docker Buildx (ускоритель сборки)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Шаг 4: Сборка и отправка
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          # Указываем, где лежит Dockerfile (относительно корня репо)
          # context: ./day02
          context: .
          push: true
          # Тегируем образ:
          # 1. latest (последняя версия)
          # 2. sha (уникальный хеш коммита - чтобы можно было откатиться)
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/spiral-app:latest
            ${{ secrets.DOCKER_USERNAME }}/spiral-app:${{ github.sha }}